FROM debian:bullseye-slim

RUN mkdir -p /opt/llamafile
COPY ./tmp/llamafile/* /opt/llamafile
COPY ./llamafile-entrypoint.sh /opt/entrypoint.sh

RUN apt-get update && \
    apt-get install -y wget findutils gzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN wget -O /usr/bin/ape https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf && \
    chmod +x /usr/bin/ape

RUN chmod +x /opt/entrypoint.sh
EXPOSE 8080

ENTRYPOINT ["sh", "/opt/entrypoint.sh"]